In [4]:
import numpy as np

In [ ]:
#Methods to create NumPy

a = np.array([1,2,3,4,5,6])
print(a)
#here two arrays should be of same size
b = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(b)

#The default type of elements in the array is float64, but you can specify explicityly
c = np.array([[1,2],[3,4]], dtype='int')
print(c.dtype)

#creating all zero elements array
zero_array = np.zeros([2,2], dtype='int')
print(zero_array)
#creating all 1's element array
ones_array = np.ones([2,4], dtype="int")
print(ones_array)
#creating an empty array
empty_array = np.empty([2,3])
print(empty_array)

#creating using arange
arr = np.arange(0,10)
print(arr)
#to create floting point numbers
arr_float = np.arange(1,2,0.2, dtype='float64')
print(arr_float)

#in the above example if we used arange to create floating numbers then it gives unpredicted count of numbers, so we can make use of linespace
arr_linspace = np.linspace(0,2,5)
print(arr_linspace)

[1 2 3 4 5 6]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
int64
[[0 0]
 [0 0]]
[[1 1 1 1]
 [1 1 1 1]]
[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]
[0 2 4 6 8]
[1.  1.2 1.4 1.6 1.8]
[0.  0.5 1.  1.5 2. ]


In [ ]:
#Attributes
arr = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(arr.ndim)
print(arr.dtype)
print(arr.shape)
print(arr.size)
print(arr.itemsize)


2
int64
(2, 6)
12
8


In [ ]:
#Array Manipulation

'''
1. Return Type:
ravel(): Returns a view of the original array whenever possible. Changes to the raveled array may affect the original array (if it’s a view).
flatten(): Returns a copy of the original array. Changes to the flattened array do not affect the original array.
2. Memory Efficiency:
ravel(): More memory-efficient because it avoids data copying when possible.
flatten(): Less memory-efficient as it always creates a new copy of the data.
3. Usage:
ravel(): Preferred when you don’t need to preserve the original data and want better performance.
flatten(): Preferred when you need to ensure that the original data remains unchanged.
'''

arr = np.array([1,2,3,4,5,6])
r = arr.reshape(2,3)
print(r)

flat_arr = r.flatten()
print(flat_arr)

ravel_arr = r.ravel()
print(ravel_arr)

'''
If for reshape if we provide arr.reshape(2,2,-1), then for last index it calculates on its own and gives the new array dimensions
'''



[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [26]:
#Basic Opeartions

#Arithmetic operators on arrays apply elementwise.
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,4,5,6])
print(a+b)
print(a@b)
print(a*b)
print(a.dot(b))

#unary opeartions
print(a.sum())
print(a.min())
print(a.prod())
print(a.mean())

#get index of max and min
print("Index of max and min")
print(a.argmax())
print(a.argmin())

reshape_arr = a.reshape(2,3)
print(reshape_arr.sum(axis=0)) #axis zero is column
print(reshape_arr.sum(axis=1)) #axis one is row



[ 2  4  6  8 10 12]
91
[ 1  4  9 16 25 36]
91
21
1
720
3.5
Index of max and min
5
0
[5 7 9]
[ 6 15]


In [ ]:
#Numpy indexing
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,13]])
print(arr[1:2,1:4])

print(arr[1:2,1:4:2])  #here we also gave step as 2

#When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

[[ 8  9 10]]
[[ 8 10]]


In [ ]:
#Ieration is done using first axis
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,13]])
for row in arr:
  print(row)

[1 2 3 4 5 6]
[ 7  8  9 10 11 13]


In [15]:
#stacking arrays

a = np.arange(0,4)
b = np.arange(6,10)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

a.reshape(2,2)
b.reshape(2,2)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

c = np.floor(10 * np.random.random((2, 2)))
d = np.floor(10 * np.random.random((2, 2)))
np.hstack((c, d))

#In general, for arrays with more than two dimensions, hstack stacks along their second axes, vstack stacks along their first axes


[[0 1 2 3]
 [6 7 8 9]]
[0 1 2 3 6 7 8 9]
[[0 1 2 3]
 [6 7 8 9]]
[0 1 2 3 6 7 8 9]


array([[2., 1., 8., 3.],
       [5., 1., 7., 1.]])

In [19]:
#splitting array
c = np.floor(10 * np.random.random((2, 10)))
d = np.floor(10 * np.random.random((2, 10)))

print(c)
print(d)

print(np.hsplit(c,2))
print(np.vsplit(c,2))



[[2. 4. 0. 4. 4. 3. 0. 2. 6. 9.]
 [0. 9. 0. 8. 8. 5. 1. 7. 4. 3.]]
[[9. 3. 6. 5. 7. 7. 8. 1. 8. 1.]
 [9. 9. 5. 6. 2. 6. 1. 1. 4. 1.]]
[array([[2., 4., 0., 4., 4.],
       [0., 9., 0., 8., 8.]]), array([[3., 0., 2., 6., 9.],
       [5., 1., 7., 4., 3.]])]
[array([[2., 4., 0., 4., 4., 3., 0., 2., 6., 9.]]), array([[0., 9., 0., 8., 8., 5., 1., 7., 4., 3.]])]


In [28]:
#Copies(deep copy) and Views(shallow copy)

#View: Different array objects can share the same data. The view method creates a new array object that looks at the same data.

print("View")
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a.view()
print(b)
b[:]=1
print(b)
print(a)
#Because b is a view of a, if we make changes in b, it reflects in a

print("Copy")

#Copy: The copy method makes a complete copy of the array and its data.
c = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
d = c.copy()
print(d)
d[:]=1
print(d)
print(c)
#Because b is a view of a, if we make changes in b, it reflects in a

'''
Note:
1.slicing creates view
2. Suppose we have a large array, then we can create a copy of it by slicing and use that and delete the original array. Here we can make use of copy

a = np.arange(int(1e8))
b = a[:100].copy()
del a
'''



View
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Copy
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [38]:
#Random Generator
#use permuted congruential generator - PCG (Psuedo generator)

from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

arr = gen(pcg(seed=45))   #mention a seed, so every time we get the same set of random numbers, we get the state of it by specifying the seed
print(arr)

#specify the distribution to generate
print(arr.normal(size=(5,5)))

#Get Integers
print(arr.integers(low=2,high=20,size=(5,5)))

#get random
print(100*arr.random(size=(5,5)))


Generator(PCG64)
[[-0.45786521 -0.62285868  0.13529003  0.84390259 -0.14849869]
 [ 0.26248378  0.53166804  0.6898073  -0.89189867  0.46882042]
 [-0.01778763 -0.6014297  -0.67763502 -0.22721533 -0.9935554 ]
 [-1.45890289  0.06375738  0.77451782 -0.24113171  0.7400469 ]
 [-0.3999656  -0.99535973 -1.52223065 -0.82025146  1.45328239]]
[[ 3  4 11  3  5]
 [ 4  7 16 17  5]
 [ 5 14  6 14  9]
 [11 17 19 15  8]
 [ 5  2  2 10  8]]
[[12.43307595 99.24931576 35.84362243 69.21962425 21.03198557]
 [ 1.35702786 97.47610633 72.331673   70.71529247 81.84107479]
 [31.91302529 43.63068654 37.49385017 87.42889538 31.59870206]
 [34.05552093 75.07293046 61.21549969 53.02470386 14.12420163]
 [38.3026769  89.92742536  9.67885073 81.20834195 67.68242306]]


In [45]:
#Broadcasting
'''
Rule:
1. The first rule of broadcasting is that if all input arrays do not have the same number of dimensions, a “1” will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions.
2. The second rule of broadcasting ensures that arrays with a size of 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension
'''
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
print(arr1+arr2)
print(arr1+4)

'''
Rule 3: If dimensions are not matching, Numpy will fail if we move from right to left and if nither of the array has 1 in right first dimension.
example: if dimensions are (1,4) and (1,5), then it gives error as if we move from right to left, we encounter first dimension as 4 or 5 and neither of them is 1, so it gives error
'''

arr3 = np.array([[1,2],[3,4]])
arr4 = np.array([1,2])
print(arr3+arr4)
'''
Here arr4 gets broadcasted to match dimensions of arr3
1 2 + 1 2 = 2 4
3 4   1 2   4 6
'''




[ 2  4  6  8 10]
[5 6 7 8 9]
[[2 4]
 [4 6]]


'\nHere arr4 gets broadcasted to match dimensions of arr3\n1 2 + 1 2 = 2 4\n3 4   1 2   4 6\n'

In [7]:
#concatenate
n = np.array([1,2,3,4,5])
m = np.array([6,7,8,9,10])
print(np.concatenate((n,m)))

n = np.array([[1,2,3],[4,5,11]])
m = np.array([[6,7,8],[9,10,18]])
print(np.concatenate((n,m)))



[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3]
 [ 4  5 11]
 [ 6  7  8]
 [ 9 10 18]]


In [15]:
#Transpose
'''
a.T is same as a.transpose()
'''
n = np.array([[1,2,3],[4,5,11]])
print(n)
a_trans = n.T
print(a_trans)

[[ 1  2  3]
 [ 4  5 11]]
[[ 1  4]
 [ 2  5]
 [ 3 11]]


In [21]:
#Delete a specific section
n = np.array([[1,2,3],[4,5,11]])
print(np.delete(n,1,axis=1))

[[ 1  3]
 [ 4 11]]


In [18]:
#Save and Load NumPy data
'''
To save your arrays to disk and load them back without having to re-run the code,
'''
a= np.array([1,2,3,4,5,6])
np.save('filename',a)
b = np.load('filename.npy')
print(b)

'''
You can also store in csv format
'''
np.savetxt('filename.csv',a)
c = np.loadtxt('filename.csv')
print(c)

[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]


In [23]:
#eye
'''
Return a 2-D array with ones on the diagonal and zeros elsewhere.
'''
print(np.eye(3))
print(np.eye(3, k=1))  #k=1 is one diagonal up

#identity
print(np.identity(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
